import pygame
from pygame.locals import *

pygame.init()

FPS = 60
FPSCLOCK = pygame.time.Clock()
WINDOWWIDTH = 1080
WINDOWHEIGHT = 720
DISPLAYSURF = pygame.display.set_mode((WINDOWWIDTH,WINDOWHEIGHT))

FONTSIZE = 20
BASICFONT = pygame.font.Font('freesansbold.ttf', FONTSIZE)

SPEECHBUBBLETOP    = 1/8 * WINDOWHEIGHT
SPEECHBUBBLELEFT   = 1/8 * WINDOWWIDTH
SPEECHBUBBLEWIDTH  = 3/4 * WINDOWWIDTH
SPEECHBUBBLEHEIGHT = 3/4 * WINDOWHEIGHT
SPEECHBUBBLEBOTTOM = SPEECHBUBBLETOP + SPEECHBUBBLEHEIGHT
SPEECHBUBBLERIGHT  = SPEECHBUBBLELEFT + SPEECHBUBBLEWIDTH

SPEECHBUBBLEMARGIN = 2 * FONTSIZE



BLACK = (  0,   0,   0)
BLUE  = (  0,   0, 255)
GREEN = (  0, 255,   0)
RED   = (255,   0,   0)
WHITE = (255, 255, 255)

UP    = [K_w, K_UP]
DOWN  = [K_s, K_DOWN]
LEFT  = [K_a, K_LEFT]
RIGHT = [K_d, K_RIGHT]
USE   = [K_e]


DEFAULTMOVEMENTPERTURN = 300