import pygame
from pygame.locals import *



FPS = 60
WINDOW_WIDTH = 1080
WINDOW_HEIGHT = 720


FONT_SIZE = 20
BASIC_FONT = pygame.font.Font('freesansbold.ttf', FONT_SIZE)

MARGIN = 2 * FONT_SIZE

SPEECH_BUBBLE_TOP          = 1/8 * WINDOW_HEIGHT
SPEECH_BUBBLE_LEFT         = 1/8 * WINDOW_WIDTH
SPEECH_BUBBLE_WIDTH        = 3/4 * WINDOW_WIDTH
SPEECH_BUBBLE_HEIGHT       = 3/4 * WINDOW_HEIGHT
SPEECH_BUBBLE_BOTTOM       = SPEECH_BUBBLE_TOP + SPEECH_BUBBLE_HEIGHT
SPEECH_BUBBLE_RIGHT        = SPEECH_BUBBLE_LEFT + SPEECH_BUBBLE_WIDTH
SPEECH_BUBBLE_FRAME_RECT   = pygame.Rect(SPEECH_BUBBLE_LEFT, SPEECH_BUBBLE_TOP, SPEECH_BUBBLE_WIDTH, SPEECH_BUBBLE_HEIGHT)
SPEECH_BUBBLE_HEADER_RECT  = pygame.Rect(SPEECH_BUBBLE_LEFT + MARGIN, SPEECH_BUBBLE_TOP + 2 * FONT_SIZE, SPEECH_BUBBLE_WIDTH - 2 * MARGIN, SPEECH_BUBBLE_HEIGHT)
SPEECH_BUBBLE_MAIN_RECT    = pygame.Rect(SPEECH_BUBBLE_LEFT + MARGIN, SPEECH_BUBBLE_TOP + 3 * FONT_SIZE, SPEECH_BUBBLE_WIDTH - 2 * MARGIN, SPEECH_BUBBLE_HEIGHT)


ACTION_BUBBLE_TOP    = 3/5 * WINDOW_HEIGHT
ACTION_BUBBLE_LEFT   = 1/20 * WINDOW_WIDTH
ACTION_BUBBLE_WIDTH  = 1/4 * WINDOW_WIDTH
ACTION_BUBBLE_HEIGHT = 1/3 * WINDOW_HEIGHT



BLACK = (  0,   0,   0)
BLUE  = (  0,   0, 255)
GREEN = (  0, 255,   0)
RED   = (255,   0,   0)
WHITE = (255, 255, 255)

UP    = [K_w, K_UP]
DOWN  = [K_s, K_DOWN]
LEFT  = [K_a, K_LEFT]
RIGHT = [K_d, K_RIGHT]
USE   = [K_e]


DEFAULT_MOVEMENT_PER_TURN = 300